import { Center } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chat Grahph | Fullstack App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cupiditate
        repudiandae blanditiis perferendis iusto quo molestias! Illum
        exercitationem architecto illo, nulla doloribus veritatis dignissimos
        minus eos saepe consectetur voluptatibus sunt velit.
      </Center>
    </>
  );
};

export default Home;
